site_name: decodedata
site_url: https://decodedataio.github.io/
#docs_dir: 'docs'  

theme:
  name: material
  custom_dir: overrides
  font:
    text: Monserrat
  
  logo: assets/DecodeDataLogo_106x106.png
  
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    #- navigation.instant
    #- navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.integrate

  language: en

  direction: ltr

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom #teal
      accent:  cyan 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: custom
      accent: cyan
      
plugins:
  - search
  #- meta
  #- blog:
  #    blog_dir: blog 
  - i18n:
      reconfigure_material: true
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: es
          name: Español
          nav_translations:
            Home: Inicio
            Reference: Referencia
            Setup: Configuración
            Grid: Grilla
            Social Cards: Tarjatas sociales

nav:
  - Home: index.md
  - Reference:
    - Grid: reference/grid.md
  - Setup:
    - Social Cards: setup/social_cards.md
  #- Blog: 
  #  - blog/index.md
  
markdown_extensions: 
  - attr_list
  - md_in_html

  # emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  
  # admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


extra_css:
  - assets/stylesheets/extra.css


# pip install mkdocs-static-i18n[material]
#extra:
#  alternate:
#    - name: en - English
#      link: /en/ 
#      lang: en
#    - name: es - Spanish
#      link: /es/
#      lang: es
  

