authors:
  nacho:
    name: Jose Ignacio RM
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/47498082
  jim:
    name: Jim Barlow
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/34912260